name: FishPlugin
version: '${project.version}'
main: silverassist.fishplugin.FishPlugin
api-version: 1.17

commands:
  rod:
    description: 釣りパワー設定コマンド
    permission: op
    permission-message: けんげんないよぉ
    usage: /rod <get/set> <power/cutline> [<amount(setのみ)>]

  fish:
    description: 釣り関係いろいろコマンド
    usage: /fish <modechange>