name: FishPlugin
version: '${project.version}'
main: silverassist.fishplugin.FishPlugin
api-version: 1.17

commands:
  fishpower:
    description: 釣りパワー設定コマンド
    permission: op
    permission-message: けんげんないよぉ
    usage: /fishpower <get/set> [<amount(setのみ)>]

  fish:
    description: 釣り関係いろいろコマンド(今はconfig-reloadのみ)
    permission: op
    permission-message: けんげんないよぉ
    usage: /fishpower <reload>